### ISSUE TITLE
Tried everything, getting TypeError: $ is not a function

### ISSUE THREAD

**Issue by lommaj** [angular-ui/ui-calendar#273]
at Scope.link.scope.destroy (calendar.js:257)

I have tried everything, moving scripts around, here is my bower.json

I can confirm jquery is on the page.  works in other directives.

```
 "dependencies": {
    "jquery": "~2.1.4",
    "angular": "~1.3.13",
    "moment": "~2.10.2",
    "lodash": "~3.6.0",
    "satellizer": "~0.9.2",
    "bootstrap": "~3.3.2",
    "angular-bootstrap": "~0.13.0",
    "angular-ui-router": "~0.2.13",
    "holderjs": "~2.5.0",
    "opentok-layout-js": "~0.1.1",
    "opentok-angular": "~0.3.0",
    "angular-ui-calendar": "~1.0.0",
    "greensock": "~1.16.1",
    "angular-animate": "~1.3.15"
  }
```

**Comment by ballerabdude** [comment]
@lommaj do you have a stack trace I can see? Also just to be sure do you also have the fullcalendar library referenced on your head tag?

**Comment by stodolos** [comment]
Were you able to get this to work with Bootstrap 3.3.x?  How about Angular 1.4.x?

**Comment by lommaj** [comment]
I havent tried it again yet, but im am going to probably use this directive
again soon.

**Comment by stodolos** [comment]
OK please keep me posted.  I wanted to use this calendar, but am using https://mattlewis.me/angular-bootstrap-calendar/ instead for now.  However, I like the displaying of events in this calendar better for my purposes.
